// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/google/trillian/log (interfaces: Operation)

package log

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
)

// MockOperation is a mock of Operation interface.
type MockOperation struct {
	ctrl     *gomock.Controller
	recorder *MockOperationMockRecorder
}

// MockOperationMockRecorder is the mock recorder for MockOperation.
type MockOperationMockRecorder struct {
	mock *MockOperation
}

// NewMockOperation creates a new mock instance.
func NewMockOperation(ctrl *gomock.Controller) *MockOperation {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperation) EXPECT() *MockOperationMockRecorder {
	_ = "STUB: not implemented"

	// ExecutePass mocks base method.
	return nil
}

func (m *MockOperation) ExecutePass(arg0 context.Context, arg1 int64, arg2 *OperationInfo) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// ExecutePass indicates an expected call of ExecutePass.
func (mr *MockOperationMockRecorder) ExecutePass(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
