// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by starcgen. DO NOT EDIT.
// File: batchmap.shims.go

package batchmap

import (
	"reflect"

	// Library imports
	"context"

	"github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime"
	"github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/exec"
	"github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/graphx/schema"
	"github.com/apache/beam/sdks/v2/go/pkg/beam/core/util/reflectx"
)

func init() {
	runtime.RegisterFunction(entryToNodeHashFn)
	runtime.RegisterFunction(partitionByPrefixLenFn)
	runtime.RegisterFunction(tileToNodeHashFn)
	runtime.RegisterType(reflect.TypeOf((*Entry)(nil)).Elem())
	schema.RegisterType(reflect.TypeOf((*Entry)(nil)).Elem())
	runtime.RegisterType(reflect.TypeOf((*Tile)(nil)).Elem())
	schema.RegisterType(reflect.TypeOf((*Tile)(nil)).Elem())
	runtime.RegisterType(reflect.TypeOf((*context.Context)(nil)).Elem())
	schema.RegisterType(reflect.TypeOf((*context.Context)(nil)).Elem())
	runtime.RegisterType(reflect.TypeOf((*leafShardFn)(nil)).Elem())
	schema.RegisterType(reflect.TypeOf((*leafShardFn)(nil)).Elem())
	runtime.RegisterType(reflect.TypeOf((*nodeHash)(nil)).Elem())
	schema.RegisterType(reflect.TypeOf((*nodeHash)(nil)).Elem())
	runtime.RegisterType(reflect.TypeOf((*tileHashFn)(nil)).Elem())
	schema.RegisterType(reflect.TypeOf((*tileHashFn)(nil)).Elem())
	runtime.RegisterType(reflect.TypeOf((*tileUpdateFn)(nil)).Elem())
	schema.RegisterType(reflect.TypeOf((*tileUpdateFn)(nil)).Elem())
	reflectx.RegisterStructWrapper(reflect.TypeOf((*leafShardFn)(nil)).Elem(), wrapMakerLeafShardFn)
	reflectx.RegisterStructWrapper(reflect.TypeOf((*tileHashFn)(nil)).Elem(), wrapMakerTileHashFn)
	reflectx.RegisterStructWrapper(reflect.TypeOf((*tileUpdateFn)(nil)).Elem(), wrapMakerTileUpdateFn)
	reflectx.RegisterFunc(reflect.TypeOf((*func(context.Context, []byte, func(*nodeHash) bool) (*Tile, error))(nil)).Elem(), funcMakerContext۰ContextSliceOfByteIterNodeHashГᏘTileError)
	reflectx.RegisterFunc(reflect.TypeOf((*func(context.Context, []byte, func(**Tile) bool, func(*nodeHash) bool) (*Tile, error))(nil)).Elem(), funcMakerContext۰ContextSliceOfByteIterᏘTileIterNodeHashГᏘTileError)
	reflectx.RegisterFunc(reflect.TypeOf((*func(nodeHash) ([]byte, nodeHash))(nil)).Elem(), funcMakerNodeHashГSliceOfByteNodeHash)
	reflectx.RegisterFunc(reflect.TypeOf((*func())(nil)).Elem(), funcMakerГ)
	reflectx.RegisterFunc(reflect.TypeOf((*func(*Entry) nodeHash)(nil)).Elem(), funcMakerᏘEntryГNodeHash)
	reflectx.RegisterFunc(reflect.TypeOf((*func(*Tile) int)(nil)).Elem(), funcMakerᏘTileГInt)
	reflectx.RegisterFunc(reflect.TypeOf((*func(*Tile) nodeHash)(nil)).Elem(), funcMakerᏘTileГNodeHash)
	exec.RegisterInput(reflect.TypeOf((*func(*nodeHash) bool)(nil)).Elem(), iterMakerNodeHash)
	exec.RegisterInput(reflect.TypeOf((*func(**Tile) bool)(nil)).Elem(), iterMakerᏘTile)
}

func wrapMakerLeafShardFn(fn any) map[string]reflectx.Func { _ = "STUB: not implemented"; return nil }

func wrapMakerTileHashFn(fn any) map[string]reflectx.Func { _ = "STUB: not implemented"; return nil }

func wrapMakerTileUpdateFn(fn any) map[string]reflectx.Func { _ = "STUB: not implemented"; return nil }

type callerContext۰ContextSliceOfByteIterNodeHashГᏘTileError struct {
	fn func(context.Context, []byte, func(*nodeHash) bool) (*Tile, error)
}

func funcMakerContext۰ContextSliceOfByteIterNodeHashГᏘTileError(fn any) reflectx.Func {
	_ = "STUB: not implemented"
	return *new(reflectx.Func)
}

func (c *callerContext۰ContextSliceOfByteIterNodeHashГᏘTileError) Name() string {
	_ = "STUB: not implemented"
	return ""
}

func (c *callerContext۰ContextSliceOfByteIterNodeHashГᏘTileError) Type() reflect.Type {
	_ = "STUB: not implemented"
	return *new(reflect.Type)
}

func (c *callerContext۰ContextSliceOfByteIterNodeHashГᏘTileError) Call(args []any) []any {
	_ = "STUB: not implemented"
	return nil
}

func (c *callerContext۰ContextSliceOfByteIterNodeHashГᏘTileError) Call3x2(arg0, arg1, arg2 any) (any, any) {
	_ = "STUB: not implemented"
	return *new(any), *new(any)
}

type callerContext۰ContextSliceOfByteIterᏘTileIterNodeHashГᏘTileError struct {
	fn func(context.Context, []byte, func(**Tile) bool, func(*nodeHash) bool) (*Tile, error)
}

func funcMakerContext۰ContextSliceOfByteIterᏘTileIterNodeHashГᏘTileError(fn any) reflectx.Func {
	_ = "STUB: not implemented"
	return *new(reflectx.Func)
}

func (c *callerContext۰ContextSliceOfByteIterᏘTileIterNodeHashГᏘTileError) Name() string {
	_ = "STUB: not implemented"
	return ""
}

func (c *callerContext۰ContextSliceOfByteIterᏘTileIterNodeHashГᏘTileError) Type() reflect.Type {
	_ = "STUB: not implemented"
	return *new(reflect.Type)
}

func (c *callerContext۰ContextSliceOfByteIterᏘTileIterNodeHashГᏘTileError) Call(args []any) []any {
	_ = "STUB: not implemented"
	return nil
}

func (c *callerContext۰ContextSliceOfByteIterᏘTileIterNodeHashГᏘTileError) Call4x2(arg0, arg1, arg2, arg3 any) (any, any) {
	_ = "STUB: not implemented"
	return *new(any), *new(any)
}

type callerNodeHashГSliceOfByteNodeHash struct {
	fn func(nodeHash) ([]byte, nodeHash)
}

func funcMakerNodeHashГSliceOfByteNodeHash(fn any) reflectx.Func {
	_ = "STUB: not implemented"
	return *new(reflectx.Func)
}

func (c *callerNodeHashГSliceOfByteNodeHash) Name() string { _ = "STUB: not implemented"; return "" }

func (c *callerNodeHashГSliceOfByteNodeHash) Type() reflect.Type {
	_ = "STUB: not implemented"
	return *new(reflect.Type)
}

func (c *callerNodeHashГSliceOfByteNodeHash) Call(args []any) []any {
	_ = "STUB: not implemented"
	return nil
}

func (c *callerNodeHashГSliceOfByteNodeHash) Call1x2(arg0 any) (any, any) {
	_ = "STUB: not implemented"
	return *new(any), *new(any)
}

type callerГ struct {
	fn func()
}

func funcMakerГ(fn any) reflectx.Func { _ = "STUB: not implemented"; return *new(reflectx.Func) }

func (c *callerГ) Name() string { _ = "STUB: not implemented"; return "" }

func (c *callerГ) Type() reflect.Type { _ = "STUB: not implemented"; return *new(reflect.Type) }

func (c *callerГ) Call(args []any) []any { _ = "STUB: not implemented"; return nil }

func (c *callerГ) Call0x0() { _ = "STUB: not implemented"; return }

type callerᏘEntryГNodeHash struct {
	fn func(*Entry) nodeHash
}

func funcMakerᏘEntryГNodeHash(fn any) reflectx.Func {
	_ = "STUB: not implemented"
	return *new(reflectx.Func)
}

func (c *callerᏘEntryГNodeHash) Name() string { _ = "STUB: not implemented"; return "" }

func (c *callerᏘEntryГNodeHash) Type() reflect.Type {
	_ = "STUB: not implemented"
	return *new(reflect.Type)
}

func (c *callerᏘEntryГNodeHash) Call(args []any) []any { _ = "STUB: not implemented"; return nil }

func (c *callerᏘEntryГNodeHash) Call1x1(arg0 any) any {
	_ = "STUB: not implemented"
	return *new(any)
}

type callerᏘTileГInt struct {
	fn func(*Tile) int
}

func funcMakerᏘTileГInt(fn any) reflectx.Func {
	_ = "STUB: not implemented"
	return *new(reflectx.Func)
}

func (c *callerᏘTileГInt) Name() string { _ = "STUB: not implemented"; return "" }

func (c *callerᏘTileГInt) Type() reflect.Type {
	_ = "STUB: not implemented"
	return *new(reflect.Type)
}

func (c *callerᏘTileГInt) Call(args []any) []any { _ = "STUB: not implemented"; return nil }

func (c *callerᏘTileГInt) Call1x1(arg0 any) any { _ = "STUB: not implemented"; return *new(any) }

type callerᏘTileГNodeHash struct {
	fn func(*Tile) nodeHash
}

func funcMakerᏘTileГNodeHash(fn any) reflectx.Func {
	_ = "STUB: not implemented"
	return *new(reflectx.Func)
}

func (c *callerᏘTileГNodeHash) Name() string { _ = "STUB: not implemented"; return "" }

func (c *callerᏘTileГNodeHash) Type() reflect.Type {
	_ = "STUB: not implemented"
	return *new(reflect.Type)
}

func (c *callerᏘTileГNodeHash) Call(args []any) []any { _ = "STUB: not implemented"; return nil }

func (c *callerᏘTileГNodeHash) Call1x1(arg0 any) any {
	_ = "STUB: not implemented"
	return *new(any)
}

type iterNative struct {
	s  exec.ReStream
	fn any

	// cur is the "current" stream, if any.
	cur exec.Stream
}

func (v *iterNative) Init() error { _ = "STUB: not implemented"; return nil }

func (v *iterNative) Value() any { _ = "STUB: not implemented"; return *new(any) }

func (v *iterNative) Reset() error { _ = "STUB: not implemented"; return nil }

func iterMakerNodeHash(s exec.ReStream) exec.ReusableInput {
	_ = "STUB: not implemented"
	return *new(exec.ReusableInput)
}

func (v *iterNative) readNodeHash(value *nodeHash) bool { _ = "STUB: not implemented"; return false }

func iterMakerᏘTile(s exec.ReStream) exec.ReusableInput {
	_ = "STUB: not implemented"
	return *new(exec.ReusableInput)
}

func (v *iterNative) readᏘTile(value **Tile) bool { _ = "STUB: not implemented"; return false }

// DO NOT MODIFY: GENERATED CODE
