// Code generated by "stringer -type=OpType types.go"; DO NOT EDIT.

package trees

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _OpType_name = "UnknownAdminQueryQueueLogSequenceLogUpdateMap"

var _OpType_index = [...]uint8{0, 7, 12, 17, 25, 36, 45}

func (i OpType) String() string { _ = "STUB: not implemented"; return "" }
