// Code generated by "stringer -type=Group quota.go"; DO NOT EDIT.

package quota

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _Group_name = "GlobalTreeUser"

var _Group_index = [...]uint8{0, 6, 10, 14}

func (i Group) String() string { _ = "STUB: not implemented"; return "" }
