// Code generated by "stringer -type=Kind quota.go"; DO NOT EDIT.

package quota

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _Kind_name = "ReadWrite"

var _Kind_index = [...]uint8{0, 4, 9}

func (i Kind) String() string { _ = "STUB: not implemented"; return "" }
