// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/google/trillian/quota (interfaces: Manager)

// Package quota is a generated GoMock package.
package quota

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	_ = "STUB: not implemented"

	// GetTokens mocks base method.
	return nil
}

func (m *MockManager) GetTokens(arg0 context.Context, arg1 int, arg2 []Spec) error {
	_ = "STUB: not implemented"
	return nil
}

// GetTokens indicates an expected call of GetTokens.
func (mr *MockManagerMockRecorder) GetTokens(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutTokens mocks base method.
func (m *MockManager) PutTokens(arg0 context.Context, arg1 int, arg2 []Spec) error {
	_ = "STUB: not implemented"
	return nil
}

// PutTokens indicates an expected call of PutTokens.
func (mr *MockManagerMockRecorder) PutTokens(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResetQuota mocks base method.
func (m *MockManager) ResetQuota(arg0 context.Context, arg1 []Spec) error {
	_ = "STUB: not implemented"
	return nil
}

// ResetQuota indicates an expected call of ResetQuota.
func (mr *MockManagerMockRecorder) ResetQuota(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
