// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/google/trillian/storage/cache (interfaces: NodeStorage)

// Package cache is a generated GoMock package.
package cache

import (
	gomock "github.com/golang/mock/gomock"
	storagepb "github.com/google/trillian/storage/storagepb"
)

// MockNodeStorage is a mock of NodeStorage interface.
type MockNodeStorage struct {
	ctrl     *gomock.Controller
	recorder *MockNodeStorageMockRecorder
}

// MockNodeStorageMockRecorder is the mock recorder for MockNodeStorage.
type MockNodeStorageMockRecorder struct {
	mock *MockNodeStorage
}

// NewMockNodeStorage creates a new mock instance.
func NewMockNodeStorage(ctrl *gomock.Controller) *MockNodeStorage {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeStorage) EXPECT() *MockNodeStorageMockRecorder {
	_ = "STUB: not implemented"

	// GetSubtree mocks base method.
	return nil
}

func (m *MockNodeStorage) GetSubtree(arg0 []byte) (*storagepb.SubtreeProto, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSubtree indicates an expected call of GetSubtree.
func (mr *MockNodeStorageMockRecorder) GetSubtree(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
