// Copyright 2017 Google LLC. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: storagepb.proto

// Package storagepb contains definitions for quota storage protos, which are
// recorded in etcd.

package storagepb

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible states of a quota configuration.
type Config_State int32

const (
	// Unknown quota state. Invalid.
	Config_UNKNOWN_CONFIG_STATE Config_State = 0
	// Quota is enabled.
	Config_ENABLED Config_State = 1
	// Quota is disabled (considered infinite).
	Config_DISABLED Config_State = 2
)

// Enum value maps for Config_State.
var (
	Config_State_name = map[int32]string{
		0: "UNKNOWN_CONFIG_STATE",
		1: "ENABLED",
		2: "DISABLED",
	}
	Config_State_value = map[string]int32{
		"UNKNOWN_CONFIG_STATE": 0,
		"ENABLED":              1,
		"DISABLED":             2,
	}
)

func (x Config_State) Enum() *Config_State { _ = "STUB: not implemented"; return nil }

func (x Config_State) String() string { _ = "STUB: not implemented"; return "" }

func (Config_State) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (Config_State) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x Config_State) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use Config_State.Descriptor instead.
func (Config_State) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// Data contained in a quota bucket.
// Stored at each each quota's zero bucket. For example,
// quotas/global/read/0 or quotas/trees/$id/read/0.
type Bucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of tokens left in the bucket.
	Tokens int64 `protobuf:"varint,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	// Timestamp of the last time the bucket got replenished.
	LastReplenishMillisSinceEpoch int64 `protobuf:"varint,2,opt,name=last_replenish_millis_since_epoch,json=lastReplenishMillisSinceEpoch,proto3" json:"last_replenish_millis_since_epoch,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Bucket) Reset() { _ = "STUB: not implemented"; return }

func (x *Bucket) String() string { _ = "STUB: not implemented"; return "" }

func (*Bucket) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Bucket) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Bucket.ProtoReflect.Descriptor instead.
func (*Bucket) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Bucket) GetTokens() int64 { _ = "STUB: not implemented"; return 0 }

func (x *Bucket) GetLastReplenishMillisSinceEpoch() int64 { _ = "STUB: not implemented"; return 0 }

// Configuration for all quotas.
// Stored at quotas/configs.
type Configs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Known quota configurations.
	Configs       []*Config `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configs) Reset() { _ = "STUB: not implemented"; return }

func (x *Configs) String() string { _ = "STUB: not implemented"; return "" }

func (*Configs) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Configs) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Configs.ProtoReflect.Descriptor instead.
func (*Configs) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Configs) GetConfigs() []*Config { _ = "STUB: not implemented"; return nil }

// Configuration of a quota.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the config, eg, “quotas/trees/1234/read/config”.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// State of the config.
	State Config_State `protobuf:"varint,2,opt,name=state,proto3,enum=storagepb.Config_State" json:"state,omitempty"`
	// Max number of tokens available for the config.
	MaxTokens int64 `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// Replenishment strategy used by the config.
	//
	// Types that are valid to be assigned to ReplenishmentStrategy:
	//
	//	*Config_SequencingBased
	//	*Config_TimeBased
	ReplenishmentStrategy isConfig_ReplenishmentStrategy `protobuf_oneof:"replenishment_strategy"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Config) Reset() { _ = "STUB: not implemented"; return }

func (x *Config) String() string { _ = "STUB: not implemented"; return "" }

func (*Config) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Config) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Config) GetName() string { _ = "STUB: not implemented"; return "" }

func (x *Config) GetState() Config_State { _ = "STUB: not implemented"; return *new(Config_State) }

func (x *Config) GetMaxTokens() int64 { _ = "STUB: not implemented"; return 0 }

func (x *Config) GetReplenishmentStrategy() isConfig_ReplenishmentStrategy {
	_ = "STUB: not implemented"
	return *new(isConfig_ReplenishmentStrategy)
}

func (x *Config) GetSequencingBased() *SequencingBasedStrategy {
	_ = "STUB: not implemented"
	return nil
}

func (x *Config) GetTimeBased() *TimeBasedStrategy { _ = "STUB: not implemented"; return nil }

type isConfig_ReplenishmentStrategy interface {
	isConfig_ReplenishmentStrategy()
}

type Config_SequencingBased struct {
	// Sequencing-based replenishment settings.
	SequencingBased *SequencingBasedStrategy `protobuf:"bytes,4,opt,name=sequencing_based,json=sequencingBased,proto3,oneof"`
}

type Config_TimeBased struct {
	// Time-based replenishment settings.
	TimeBased *TimeBasedStrategy `protobuf:"bytes,5,opt,name=time_based,json=timeBased,proto3,oneof"`
}

func (*Config_SequencingBased) isConfig_ReplenishmentStrategy() { _ = "STUB: not implemented"; return }

func (*Config_TimeBased) isConfig_ReplenishmentStrategy() {
	_ = "STUB: not implemented"

	// Sequencing-based replenishment strategy settings.
	return
}

type SequencingBasedStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequencingBasedStrategy) Reset() { _ = "STUB: not implemented"; return }

func (x *SequencingBasedStrategy) String() string { _ = "STUB: not implemented"; return "" }

func (*SequencingBasedStrategy) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *SequencingBasedStrategy) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use SequencingBasedStrategy.ProtoReflect.Descriptor instead.
func (*SequencingBasedStrategy) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Time-based replenishment strategy settings.
type TimeBasedStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of tokens to replenish at every replenish_interval_seconds.
	TokensToReplenish int64 `protobuf:"varint,1,opt,name=tokens_to_replenish,json=tokensToReplenish,proto3" json:"tokens_to_replenish,omitempty"`
	// Interval at which tokens_to_replenish get replenished.
	ReplenishIntervalSeconds int64 `protobuf:"varint,2,opt,name=replenish_interval_seconds,json=replenishIntervalSeconds,proto3" json:"replenish_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TimeBasedStrategy) Reset() { _ = "STUB: not implemented"; return }

func (x *TimeBasedStrategy) String() string { _ = "STUB: not implemented"; return "" }

func (*TimeBasedStrategy) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *TimeBasedStrategy) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use TimeBasedStrategy.ProtoReflect.Descriptor instead.
func (*TimeBasedStrategy) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *TimeBasedStrategy) GetTokensToReplenish() int64 { _ = "STUB: not implemented"; return 0 }

func (x *TimeBasedStrategy) GetReplenishIntervalSeconds() int64 {
	_ = "STUB: not implemented"
	return 0
}

var File_storagepb_proto protoreflect.FileDescriptor

const file_storagepb_proto_rawDesc = "" +
	"\n" +
	"\x0fstoragepb.proto\x12\tstoragepb\"j\n" +
	"\x06Bucket\x12\x16\n" +
	"\x06tokens\x18\x01 \x01(\x03R\x06tokens\x12H\n" +
	"!last_replenish_millis_since_epoch\x18\x02 \x01(\x03R\x1dlastReplenishMillisSinceEpoch\"6\n" +
	"\aConfigs\x12+\n" +
	"\aconfigs\x18\x01 \x03(\v2\x11.storagepb.ConfigR\aconfigs\"\xd2\x02\n" +
	"\x06Config\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.storagepb.Config.StateR\x05state\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x03R\tmaxTokens\x12O\n" +
	"\x10sequencing_based\x18\x04 \x01(\v2\".storagepb.SequencingBasedStrategyH\x00R\x0fsequencingBased\x12=\n" +
	"\n" +
	"time_based\x18\x05 \x01(\v2\x1c.storagepb.TimeBasedStrategyH\x00R\ttimeBased\"<\n" +
	"\x05State\x12\x18\n" +
	"\x14UNKNOWN_CONFIG_STATE\x10\x00\x12\v\n" +
	"\aENABLED\x10\x01\x12\f\n" +
	"\bDISABLED\x10\x02B\x18\n" +
	"\x16replenishment_strategy\"\x19\n" +
	"\x17SequencingBasedStrategy\"\x81\x01\n" +
	"\x11TimeBasedStrategy\x12.\n" +
	"\x13tokens_to_replenish\x18\x01 \x01(\x03R\x11tokensToReplenish\x12<\n" +
	"\x1areplenish_interval_seconds\x18\x02 \x01(\x03R\x18replenishIntervalSecondsB1Z/github.com/google/trillian/quota/etcd/storagepbb\x06proto3"

var (
	file_storagepb_proto_rawDescOnce sync.Once
	file_storagepb_proto_rawDescData []byte
)

func file_storagepb_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_storagepb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storagepb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_storagepb_proto_goTypes = []any{
	(Config_State)(0),               // 0: storagepb.Config.State
	(*Bucket)(nil),                  // 1: storagepb.Bucket
	(*Configs)(nil),                 // 2: storagepb.Configs
	(*Config)(nil),                  // 3: storagepb.Config
	(*SequencingBasedStrategy)(nil), // 4: storagepb.SequencingBasedStrategy
	(*TimeBasedStrategy)(nil),       // 5: storagepb.TimeBasedStrategy
}
var file_storagepb_proto_depIdxs = []int32{
	3, // 0: storagepb.Configs.configs:type_name -> storagepb.Config
	0, // 1: storagepb.Config.state:type_name -> storagepb.Config.State
	4, // 2: storagepb.Config.sequencing_based:type_name -> storagepb.SequencingBasedStrategy
	5, // 3: storagepb.Config.time_based:type_name -> storagepb.TimeBasedStrategy
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init()                      { file_storagepb_proto_init() }
func file_storagepb_proto_init() { _ = "STUB: not implemented"; return }
