// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/google/trillian/storage (interfaces: AdminStorage,AdminTX,LogStorage,LogTreeTX,ReadOnlyAdminTX,ReadOnlyLogTreeTX)

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	time "time"

	gomock "github.com/golang/mock/gomock"
	trillian "github.com/google/trillian"
	tree "github.com/google/trillian/storage/tree"
	compact "github.com/transparency-dev/merkle/compact"
)

// MockAdminStorage is a mock of AdminStorage interface.
type MockAdminStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAdminStorageMockRecorder
}

// MockAdminStorageMockRecorder is the mock recorder for MockAdminStorage.
type MockAdminStorageMockRecorder struct {
	mock *MockAdminStorage
}

// NewMockAdminStorage creates a new mock instance.
func NewMockAdminStorage(ctrl *gomock.Controller) *MockAdminStorage {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminStorage) EXPECT() *MockAdminStorageMockRecorder {
	_ = "STUB: not implemented"

	// CheckDatabaseAccessible mocks base method.
	return nil
}

func (m *MockAdminStorage) CheckDatabaseAccessible(arg0 context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// CheckDatabaseAccessible indicates an expected call of CheckDatabaseAccessible.
func (mr *MockAdminStorageMockRecorder) CheckDatabaseAccessible(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadWriteTransaction mocks base method.
func (m *MockAdminStorage) ReadWriteTransaction(arg0 context.Context, arg1 AdminTXFunc) error {
	_ = "STUB: not implemented"
	return nil
}

// ReadWriteTransaction indicates an expected call of ReadWriteTransaction.
func (mr *MockAdminStorageMockRecorder) ReadWriteTransaction(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Snapshot mocks base method.
func (m *MockAdminStorage) Snapshot(arg0 context.Context) (ReadOnlyAdminTX, error) {
	_ = "STUB: not implemented"
	return *new(ReadOnlyAdminTX), nil
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockAdminStorageMockRecorder) Snapshot(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockAdminTX is a mock of AdminTX interface.
type MockAdminTX struct {
	ctrl     *gomock.Controller
	recorder *MockAdminTXMockRecorder
}

// MockAdminTXMockRecorder is the mock recorder for MockAdminTX.
type MockAdminTXMockRecorder struct {
	mock *MockAdminTX
}

// NewMockAdminTX creates a new mock instance.
func NewMockAdminTX(ctrl *gomock.Controller) *MockAdminTX { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminTX) EXPECT() *MockAdminTXMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockAdminTX) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockAdminTXMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Commit mocks base method.
func (m *MockAdminTX) Commit() error { _ = "STUB: not implemented"; return nil }

// Commit indicates an expected call of Commit.
func (mr *MockAdminTXMockRecorder) Commit() *gomock.Call { _ = "STUB: not implemented"; return nil }

// CreateTree mocks base method.
func (m *MockAdminTX) CreateTree(arg0 context.Context, arg1 *trillian.Tree) (*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateTree indicates an expected call of CreateTree.
func (mr *MockAdminTXMockRecorder) CreateTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTree mocks base method.
func (m *MockAdminTX) GetTree(arg0 context.Context, arg1 int64) (*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetTree indicates an expected call of GetTree.
func (mr *MockAdminTXMockRecorder) GetTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HardDeleteTree mocks base method.
func (m *MockAdminTX) HardDeleteTree(arg0 context.Context, arg1 int64) error {
	_ = "STUB: not implemented"
	return nil
}

// HardDeleteTree indicates an expected call of HardDeleteTree.
func (mr *MockAdminTXMockRecorder) HardDeleteTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListTrees mocks base method.
func (m *MockAdminTX) ListTrees(arg0 context.Context, arg1 bool) ([]*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTrees indicates an expected call of ListTrees.
func (mr *MockAdminTXMockRecorder) ListTrees(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SoftDeleteTree mocks base method.
func (m *MockAdminTX) SoftDeleteTree(arg0 context.Context, arg1 int64) (*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SoftDeleteTree indicates an expected call of SoftDeleteTree.
func (mr *MockAdminTXMockRecorder) SoftDeleteTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UndeleteTree mocks base method.
func (m *MockAdminTX) UndeleteTree(arg0 context.Context, arg1 int64) (*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UndeleteTree indicates an expected call of UndeleteTree.
func (mr *MockAdminTXMockRecorder) UndeleteTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateTree mocks base method.
func (m *MockAdminTX) UpdateTree(arg0 context.Context, arg1 int64, arg2 func(*trillian.Tree)) (*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateTree indicates an expected call of UpdateTree.
func (mr *MockAdminTXMockRecorder) UpdateTree(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockLogStorage is a mock of LogStorage interface.
type MockLogStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLogStorageMockRecorder
}

// MockLogStorageMockRecorder is the mock recorder for MockLogStorage.
type MockLogStorageMockRecorder struct {
	mock *MockLogStorage
}

// NewMockLogStorage creates a new mock instance.
func NewMockLogStorage(ctrl *gomock.Controller) *MockLogStorage {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogStorage) EXPECT() *MockLogStorageMockRecorder {
	_ = "STUB: not implemented"

	// AddSequencedLeaves mocks base method.
	return nil
}

func (m *MockLogStorage) AddSequencedLeaves(arg0 context.Context, arg1 *trillian.Tree, arg2 []*trillian.LogLeaf, arg3 time.Time) ([]*trillian.QueuedLogLeaf, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AddSequencedLeaves indicates an expected call of AddSequencedLeaves.
func (mr *MockLogStorageMockRecorder) AddSequencedLeaves(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CheckDatabaseAccessible mocks base method.
func (m *MockLogStorage) CheckDatabaseAccessible(arg0 context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// CheckDatabaseAccessible indicates an expected call of CheckDatabaseAccessible.
func (mr *MockLogStorageMockRecorder) CheckDatabaseAccessible(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetActiveLogIDs mocks base method.
func (m *MockLogStorage) GetActiveLogIDs(arg0 context.Context) ([]int64, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetActiveLogIDs indicates an expected call of GetActiveLogIDs.
func (mr *MockLogStorageMockRecorder) GetActiveLogIDs(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// QueueLeaves mocks base method.
func (m *MockLogStorage) QueueLeaves(arg0 context.Context, arg1 *trillian.Tree, arg2 []*trillian.LogLeaf, arg3 time.Time) ([]*trillian.QueuedLogLeaf, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QueueLeaves indicates an expected call of QueueLeaves.
func (mr *MockLogStorageMockRecorder) QueueLeaves(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadWriteTransaction mocks base method.
func (m *MockLogStorage) ReadWriteTransaction(arg0 context.Context, arg1 *trillian.Tree, arg2 LogTXFunc) error {
	_ = "STUB: not implemented"
	return nil
}

// ReadWriteTransaction indicates an expected call of ReadWriteTransaction.
func (mr *MockLogStorageMockRecorder) ReadWriteTransaction(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SnapshotForTree mocks base method.
func (m *MockLogStorage) SnapshotForTree(arg0 context.Context, arg1 *trillian.Tree) (ReadOnlyLogTreeTX, error) {
	_ = "STUB: not implemented"
	return *new(ReadOnlyLogTreeTX), nil
}

// SnapshotForTree indicates an expected call of SnapshotForTree.
func (mr *MockLogStorageMockRecorder) SnapshotForTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockLogTreeTX is a mock of LogTreeTX interface.
type MockLogTreeTX struct {
	ctrl     *gomock.Controller
	recorder *MockLogTreeTXMockRecorder
}

// MockLogTreeTXMockRecorder is the mock recorder for MockLogTreeTX.
type MockLogTreeTXMockRecorder struct {
	mock *MockLogTreeTX
}

// NewMockLogTreeTX creates a new mock instance.
func NewMockLogTreeTX(ctrl *gomock.Controller) *MockLogTreeTX {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogTreeTX) EXPECT() *MockLogTreeTXMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockLogTreeTX) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockLogTreeTXMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Commit mocks base method.
func (m *MockLogTreeTX) Commit(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Commit indicates an expected call of Commit.
func (mr *MockLogTreeTXMockRecorder) Commit(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DequeueLeaves mocks base method.
func (m *MockLogTreeTX) DequeueLeaves(arg0 context.Context, arg1 int, arg2 time.Time) ([]*trillian.LogLeaf, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DequeueLeaves indicates an expected call of DequeueLeaves.
func (mr *MockLogTreeTXMockRecorder) DequeueLeaves(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLeavesByHash mocks base method.
func (m *MockLogTreeTX) GetLeavesByHash(arg0 context.Context, arg1 [][]byte, arg2 bool) ([]*trillian.LogLeaf, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetLeavesByHash indicates an expected call of GetLeavesByHash.
func (mr *MockLogTreeTXMockRecorder) GetLeavesByHash(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLeavesByRange mocks base method.
func (m *MockLogTreeTX) GetLeavesByRange(arg0 context.Context, arg1, arg2 int64) ([]*trillian.LogLeaf, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetLeavesByRange indicates an expected call of GetLeavesByRange.
func (mr *MockLogTreeTXMockRecorder) GetLeavesByRange(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetMerkleNodes mocks base method.
func (m *MockLogTreeTX) GetMerkleNodes(arg0 context.Context, arg1 []compact.NodeID) ([]tree.Node, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMerkleNodes indicates an expected call of GetMerkleNodes.
func (mr *MockLogTreeTXMockRecorder) GetMerkleNodes(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LatestSignedLogRoot mocks base method.
func (m *MockLogTreeTX) LatestSignedLogRoot(arg0 context.Context) (*trillian.SignedLogRoot, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LatestSignedLogRoot indicates an expected call of LatestSignedLogRoot.
func (mr *MockLogTreeTXMockRecorder) LatestSignedLogRoot(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetMerkleNodes mocks base method.
func (m *MockLogTreeTX) SetMerkleNodes(arg0 context.Context, arg1 []tree.Node) error {
	_ = "STUB: not implemented"
	return nil
}

// SetMerkleNodes indicates an expected call of SetMerkleNodes.
func (mr *MockLogTreeTXMockRecorder) SetMerkleNodes(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StoreSignedLogRoot mocks base method.
func (m *MockLogTreeTX) StoreSignedLogRoot(arg0 context.Context, arg1 *trillian.SignedLogRoot) error {
	_ = "STUB: not implemented"
	return nil
}

// StoreSignedLogRoot indicates an expected call of StoreSignedLogRoot.
func (mr *MockLogTreeTXMockRecorder) StoreSignedLogRoot(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateSequencedLeaves mocks base method.
func (m *MockLogTreeTX) UpdateSequencedLeaves(arg0 context.Context, arg1 []*trillian.LogLeaf) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateSequencedLeaves indicates an expected call of UpdateSequencedLeaves.
func (mr *MockLogTreeTXMockRecorder) UpdateSequencedLeaves(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockReadOnlyAdminTX is a mock of ReadOnlyAdminTX interface.
type MockReadOnlyAdminTX struct {
	ctrl     *gomock.Controller
	recorder *MockReadOnlyAdminTXMockRecorder
}

// MockReadOnlyAdminTXMockRecorder is the mock recorder for MockReadOnlyAdminTX.
type MockReadOnlyAdminTXMockRecorder struct {
	mock *MockReadOnlyAdminTX
}

// NewMockReadOnlyAdminTX creates a new mock instance.
func NewMockReadOnlyAdminTX(ctrl *gomock.Controller) *MockReadOnlyAdminTX {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadOnlyAdminTX) EXPECT() *MockReadOnlyAdminTXMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockReadOnlyAdminTX) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockReadOnlyAdminTXMockRecorder) Close() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Commit mocks base method.
func (m *MockReadOnlyAdminTX) Commit() error { _ = "STUB: not implemented"; return nil }

// Commit indicates an expected call of Commit.
func (mr *MockReadOnlyAdminTXMockRecorder) Commit() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTree mocks base method.
func (m *MockReadOnlyAdminTX) GetTree(arg0 context.Context, arg1 int64) (*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetTree indicates an expected call of GetTree.
func (mr *MockReadOnlyAdminTXMockRecorder) GetTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListTrees mocks base method.
func (m *MockReadOnlyAdminTX) ListTrees(arg0 context.Context, arg1 bool) ([]*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTrees indicates an expected call of ListTrees.
func (mr *MockReadOnlyAdminTXMockRecorder) ListTrees(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockReadOnlyLogTreeTX is a mock of ReadOnlyLogTreeTX interface.
type MockReadOnlyLogTreeTX struct {
	ctrl     *gomock.Controller
	recorder *MockReadOnlyLogTreeTXMockRecorder
}

// MockReadOnlyLogTreeTXMockRecorder is the mock recorder for MockReadOnlyLogTreeTX.
type MockReadOnlyLogTreeTXMockRecorder struct {
	mock *MockReadOnlyLogTreeTX
}

// NewMockReadOnlyLogTreeTX creates a new mock instance.
func NewMockReadOnlyLogTreeTX(ctrl *gomock.Controller) *MockReadOnlyLogTreeTX {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadOnlyLogTreeTX) EXPECT() *MockReadOnlyLogTreeTXMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockReadOnlyLogTreeTX) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockReadOnlyLogTreeTXMockRecorder) Close() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Commit mocks base method.
func (m *MockReadOnlyLogTreeTX) Commit(arg0 context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// Commit indicates an expected call of Commit.
func (mr *MockReadOnlyLogTreeTXMockRecorder) Commit(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLeavesByHash mocks base method.
func (m *MockReadOnlyLogTreeTX) GetLeavesByHash(arg0 context.Context, arg1 [][]byte, arg2 bool) ([]*trillian.LogLeaf, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetLeavesByHash indicates an expected call of GetLeavesByHash.
func (mr *MockReadOnlyLogTreeTXMockRecorder) GetLeavesByHash(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLeavesByRange mocks base method.
func (m *MockReadOnlyLogTreeTX) GetLeavesByRange(arg0 context.Context, arg1, arg2 int64) ([]*trillian.LogLeaf, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetLeavesByRange indicates an expected call of GetLeavesByRange.
func (mr *MockReadOnlyLogTreeTXMockRecorder) GetLeavesByRange(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetMerkleNodes mocks base method.
func (m *MockReadOnlyLogTreeTX) GetMerkleNodes(arg0 context.Context, arg1 []compact.NodeID) ([]tree.Node, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetMerkleNodes indicates an expected call of GetMerkleNodes.
func (mr *MockReadOnlyLogTreeTXMockRecorder) GetMerkleNodes(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LatestSignedLogRoot mocks base method.
func (m *MockReadOnlyLogTreeTX) LatestSignedLogRoot(arg0 context.Context) (*trillian.SignedLogRoot, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LatestSignedLogRoot indicates an expected call of LatestSignedLogRoot.
func (mr *MockReadOnlyLogTreeTXMockRecorder) LatestSignedLogRoot(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
