// Copyright 2023 Google LLC. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: options.proto

package mysqlpb

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StorageOptions contains configuration parameters for MySQL implementation
// of the storage backend. This is envisioned only to be used for changes that
// would be breaking, but need to support old behaviour for backwards compatibility.
type StorageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subtreeRevisions being explicitly set to false will skip writing subtree revisions.
	// https://github.com/google/trillian/pull/3201
	SubtreeRevisions bool `protobuf:"varint,1,opt,name=subtreeRevisions,proto3" json:"subtreeRevisions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StorageOptions) Reset() { _ = "STUB: not implemented"; return }

func (x *StorageOptions) String() string { _ = "STUB: not implemented"; return "" }

func (*StorageOptions) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StorageOptions) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StorageOptions.ProtoReflect.Descriptor instead.
func (*StorageOptions) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StorageOptions) GetSubtreeRevisions() bool { _ = "STUB: not implemented"; return false }

var File_options_proto protoreflect.FileDescriptor

const file_options_proto_rawDesc = "" +
	"\n" +
	"\roptions.proto\x12\amysqlpb\"<\n" +
	"\x0eStorageOptions\x12*\n" +
	"\x10subtreeRevisions\x18\x01 \x01(\bR\x10subtreeRevisionsB2Z0github.com/google/trillian/storage/mysql/mysqlpbb\x06proto3"

var (
	file_options_proto_rawDescOnce sync.Once
	file_options_proto_rawDescData []byte
)

func file_options_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_options_proto_goTypes = []any{
	(*StorageOptions)(nil), // 0: mysqlpb.StorageOptions
}
var file_options_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                    { file_options_proto_init() }
func file_options_proto_init() { _ = "STUB: not implemented"; return }
