// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/google/trillian (interfaces: TrillianAdminServer)

// Package tmock is a generated GoMock package.
package tmock

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	trillian "github.com/google/trillian"
)

// MockTrillianAdminServer is a mock of TrillianAdminServer interface.
type MockTrillianAdminServer struct {
	ctrl     *gomock.Controller
	recorder *MockTrillianAdminServerMockRecorder
}

// MockTrillianAdminServerMockRecorder is the mock recorder for MockTrillianAdminServer.
type MockTrillianAdminServerMockRecorder struct {
	mock *MockTrillianAdminServer
}

// NewMockTrillianAdminServer creates a new mock instance.
func NewMockTrillianAdminServer(ctrl *gomock.Controller) *MockTrillianAdminServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrillianAdminServer) EXPECT() *MockTrillianAdminServerMockRecorder {
	_ = "STUB: not implemented"

	// CreateTree mocks base method.
	return nil
}

func (m *MockTrillianAdminServer) CreateTree(arg0 context.Context, arg1 *trillian.CreateTreeRequest) (*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateTree indicates an expected call of CreateTree.
func (mr *MockTrillianAdminServerMockRecorder) CreateTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteTree mocks base method.
func (m *MockTrillianAdminServer) DeleteTree(arg0 context.Context, arg1 *trillian.DeleteTreeRequest) (*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteTree indicates an expected call of DeleteTree.
func (mr *MockTrillianAdminServerMockRecorder) DeleteTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTree mocks base method.
func (m *MockTrillianAdminServer) GetTree(arg0 context.Context, arg1 *trillian.GetTreeRequest) (*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetTree indicates an expected call of GetTree.
func (mr *MockTrillianAdminServerMockRecorder) GetTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListTrees mocks base method.
func (m *MockTrillianAdminServer) ListTrees(arg0 context.Context, arg1 *trillian.ListTreesRequest) (*trillian.ListTreesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTrees indicates an expected call of ListTrees.
func (mr *MockTrillianAdminServerMockRecorder) ListTrees(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UndeleteTree mocks base method.
func (m *MockTrillianAdminServer) UndeleteTree(arg0 context.Context, arg1 *trillian.UndeleteTreeRequest) (*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UndeleteTree indicates an expected call of UndeleteTree.
func (mr *MockTrillianAdminServerMockRecorder) UndeleteTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateTree mocks base method.
func (m *MockTrillianAdminServer) UpdateTree(arg0 context.Context, arg1 *trillian.UpdateTreeRequest) (*trillian.Tree, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateTree indicates an expected call of UpdateTree.
func (mr *MockTrillianAdminServerMockRecorder) UpdateTree(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
