// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/google/trillian (interfaces: TrillianLogServer)

// Package tmock is a generated GoMock package.
package tmock

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	trillian "github.com/google/trillian"
)

// MockTrillianLogServer is a mock of TrillianLogServer interface.
type MockTrillianLogServer struct {
	ctrl     *gomock.Controller
	recorder *MockTrillianLogServerMockRecorder
}

// MockTrillianLogServerMockRecorder is the mock recorder for MockTrillianLogServer.
type MockTrillianLogServerMockRecorder struct {
	mock *MockTrillianLogServer
}

// NewMockTrillianLogServer creates a new mock instance.
func NewMockTrillianLogServer(ctrl *gomock.Controller) *MockTrillianLogServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrillianLogServer) EXPECT() *MockTrillianLogServerMockRecorder {
	_ = "STUB: not implemented"

	// AddSequencedLeaves mocks base method.
	return nil
}

func (m *MockTrillianLogServer) AddSequencedLeaves(arg0 context.Context, arg1 *trillian.AddSequencedLeavesRequest) (*trillian.AddSequencedLeavesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AddSequencedLeaves indicates an expected call of AddSequencedLeaves.
func (mr *MockTrillianLogServerMockRecorder) AddSequencedLeaves(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetConsistencyProof mocks base method.
func (m *MockTrillianLogServer) GetConsistencyProof(arg0 context.Context, arg1 *trillian.GetConsistencyProofRequest) (*trillian.GetConsistencyProofResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetConsistencyProof indicates an expected call of GetConsistencyProof.
func (mr *MockTrillianLogServerMockRecorder) GetConsistencyProof(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEntryAndProof mocks base method.
func (m *MockTrillianLogServer) GetEntryAndProof(arg0 context.Context, arg1 *trillian.GetEntryAndProofRequest) (*trillian.GetEntryAndProofResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEntryAndProof indicates an expected call of GetEntryAndProof.
func (mr *MockTrillianLogServerMockRecorder) GetEntryAndProof(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInclusionProof mocks base method.
func (m *MockTrillianLogServer) GetInclusionProof(arg0 context.Context, arg1 *trillian.GetInclusionProofRequest) (*trillian.GetInclusionProofResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetInclusionProof indicates an expected call of GetInclusionProof.
func (mr *MockTrillianLogServerMockRecorder) GetInclusionProof(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInclusionProofByHash mocks base method.
func (m *MockTrillianLogServer) GetInclusionProofByHash(arg0 context.Context, arg1 *trillian.GetInclusionProofByHashRequest) (*trillian.GetInclusionProofByHashResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetInclusionProofByHash indicates an expected call of GetInclusionProofByHash.
func (mr *MockTrillianLogServerMockRecorder) GetInclusionProofByHash(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLatestSignedLogRoot mocks base method.
func (m *MockTrillianLogServer) GetLatestSignedLogRoot(arg0 context.Context, arg1 *trillian.GetLatestSignedLogRootRequest) (*trillian.GetLatestSignedLogRootResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetLatestSignedLogRoot indicates an expected call of GetLatestSignedLogRoot.
func (mr *MockTrillianLogServerMockRecorder) GetLatestSignedLogRoot(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLeavesByRange mocks base method.
func (m *MockTrillianLogServer) GetLeavesByRange(arg0 context.Context, arg1 *trillian.GetLeavesByRangeRequest) (*trillian.GetLeavesByRangeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetLeavesByRange indicates an expected call of GetLeavesByRange.
func (mr *MockTrillianLogServerMockRecorder) GetLeavesByRange(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InitLog mocks base method.
func (m *MockTrillianLogServer) InitLog(arg0 context.Context, arg1 *trillian.InitLogRequest) (*trillian.InitLogResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// InitLog indicates an expected call of InitLog.
func (mr *MockTrillianLogServerMockRecorder) InitLog(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// QueueLeaf mocks base method.
func (m *MockTrillianLogServer) QueueLeaf(arg0 context.Context, arg1 *trillian.QueueLeafRequest) (*trillian.QueueLeafResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QueueLeaf indicates an expected call of QueueLeaf.
func (mr *MockTrillianLogServerMockRecorder) QueueLeaf(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
